In [1]:
import torch
from torch.utils.data import DataLoader, Dataset

# Set the global seed
seed = 42

class MyDataset(Dataset):
    def __len__(self):
        return 5
    
    def __getitem__(self, index):
        # Return some data sample
        return index
torch.manual_seed(seed)  # Reset seed before first pass

# Initialize DataLoader with shuffle=True
dataset = MyDataset()
data_loader = DataLoader(dataset, shuffle=True, batch_size=32)

# First pass
for epoch in range(5):
    for data in data_loader:
        print(data)
        # Your processing code here
        pass

tensor([3, 2, 1, 4, 0])
tensor([4, 0, 1, 2, 3])
tensor([1, 4, 3, 2, 0])
tensor([4, 1, 0, 3, 2])
tensor([4, 2, 3, 1, 0])
